//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP918VB_FEDIN_NESMELOV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int ID { get; set; }
        public decimal Cash { get; set; }
        public short Card { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
