//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP918VB_FEDIN_NESMELOV.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        public int IdUser { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdRole { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
